#!/bin/bash
#| Writes into primary clipboard.
#| Accepts piped input.
#| Or array of arguments will be put into clipboard.
[[ $1 == -h ]] && grep '^#|' $0 | sed 's/^#//' && exit

if [ -p /dev/stdin ]; then
    cat | wl-copy
else
    [ -z "$1" ] && exit 2
    echo "$@" | wl-copy
fi

