#!/bin/bash
status=$(systemctl is-active cronie)

if [ -z $1 ];then
	exit 1
fi

if [ $status == "active" ];then
	ERR=$(crontab $1 2>&1)
	[ -z $ERR ] && notify-send "Crontab updated" || notify-send -u critical "crontab: $ERR"
else
	notify-send -u critical "crond status: $status"
fi
