" Do not EDIT this file
" This file got generated the last time you edited autoload/ directory. And sourced at startup.
"
" Functions tagged with Listme: and description will be listed here. Providing command `List`
command! TabNameI call util#set_tabname_i()
command! Conf exe 'silent !$TERMINAL -d $VIMRUNTIME -e $EDITOR &'
