#!/bin/bash
LOGFILE=/tmp/$(basename $0).log

echo "[ $(date) ] Begin sys-backup {{{1" >> $LOGFILE
OUT=$(backup-home-config 2> /tmp/err)
EX=$?
ERR=$(</tmp/err)

echo $OUT >> $LOGFILE
echo $ERR >> $LOGFILE

export DISPLAY=:0
export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus

if [ -z $EX ];then
	notify-send "Home config backup successful."
elif [ $EX -ne 255 ];then
	notify-send -u critical "Home config backup unsuccessful! LOG: $LOGFILE"
else 
	notify-send "NOTHING TO DO."
fi
