#!/bin/bash
LOGFILE=/tmp/$(basename $0).log

echo "[ $(date) ] Begin sys-backup {{{1" >> $LOGFILE
backup-home-config &>> /tmp/sys-backup.log
EX=$?

export DISPLAY=:0
export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus

if [ $EX -eq 0 ];then
	notify-send "Home config backup successful."
elif [ $EX -ne 255 ];then
	notify-send -u critical "Home config backup unsuccessful! LOG: $LOGFILE"
else 
	notify-send "NOTHING TO DO."
fi
