#!/bin/bash
# @dotfile
# @dotdep grim corrupter swaylock

images=()
swaylock_args=()

for output in $(swaymsg -t get_outputs | jq -r '.[] .name'); do
  image=$(mktemp --suffix=.png)
  images+=($image)
  swaylock_args+=(-i $output:$image)
  grim -o $output $image
done

corrupter -mag 1 -boffset 1 ${images[@]} ${images[@]}

swaylock ${swaylock_args[@]} -s center
rm ${images[@]}
