#!/bin/bash
# @dotfile
# @dotdep grim corrupter swaylock

images=()
swaylock_args=(--daemonize)

for output in $(swaymsg -t get_outputs | jq -r '.[] .name'); do
  image=$(mktemp --suffix=.png)
  images+=($image)
  swaylock_args+=(-i $output:$image)
  grim -o $output $image
done

for image in ${images[@]}; do
  corrupter -mag 1 -boffset 1 $image $image
done

swaylock ${swaylock_args[@]} -s center

rm ${images[@]}
