#!/bin/bash
# @dotfile

MARKER=@dotfile
ARCHIVE=/tmp/homeconfig.tar.gz

cd $HOME

# For some reason when using ag --files-with-matches there is no output
# if running in crontab. For this reason --vimgrep + cut is used.
CONF=$(\
	ag \
		--ignore yank \
		--vimgrep \
		--hidden \
		--max-count=1 \
		--silent $MARKER \
	./.config \
	| cut -f 1 -d ':'\
)

SCRIPTS_PROGS=$(\
	find ./.scripts ./.progs -type f \
	| cut -f2 \
	| ag --invert-match '(github|target|\.git)'\
)

tar cf $ARCHIVE $CONF $SCRIPTS_PROGS

echo -n $ARCHIVE
