#!/bin/bash
# @dotfile 
set -e

REP=git@github.com:talbergs/-.git
STAGE=/tmp/homeconfig

rm -rf $STAGE 2>/dev/null
mkdir $STAGE && cd $_

git clone --depth=1 $REP .
rm -rf $(find . -mindepth 1 -maxdepth 1 ! -name .git)
tar xf $(archive-home-config)

DIFF="$(git diff)"

if [ -z "$(git status --porcelain)" ]; then
	echo nothing to do
	exit 255
else
	IFS=$'\n'
	echo "DIFF {{{1" 1>&2
	for line in $(git diff);do
		echo "$line" 1>&2
	done
	echo "}}}1" 1>&2

	git add .
	git commit -m "automated commit $(date)"
	git push
fi

