#!/bin/bash
# @dotfile 

REP=git@github.com:talbergs/-.git
STAGE=/tmp/homeconfig

rm -rf $STAGE 2>/dev/null
mkdir $STAGE && cd $_

git clone --depth=1 $REP .
rm -rf $(find . -mindepth 1 -maxdepth 1 ! -name .git)
tar xf $(archive-home-config)

DIFF="$(git diff)"

if [ ! -z "$DIFF" ]; then
	git add .
	git commit -m "automated commit $(date)"
	git push
	exit $?
else
	echo nothing to do
	exit 255
fi

