#!/bin/bash
# @dotreadme 1: This readme is extracted from actual config, thus it is up to date.

# @dot TODO: implement to be used in backup-homeconfig
# @dot TODO: solve cross dependency maintenance in scripts
# @dot TODO: rename dot related scripts with prefix dot-<action>
ag --vimgrep @dotreadme $(tar tf $(archive-home-config))
