#!/bin/bash

export NVIM_COC_LOG_LEVEL=debug
export VIMCONFIG=$HOME/.config/vide # needed for coc.nvim
export VIMRUNTIME=$HOME/.config/vide
nvim-nightly -u "$VIMRUNTIME/init.vim" $@

# ALSO WORKING APPROACH
# nvim-nightly \
# -u ~/.config/vide/init.vim \
# --cmd 'let $VIMRUNTIME="~/.config/vide"' \
# --cmd 'runtime! $VIMRUNTIME' \
# $@
