#!/bin/bash
preval() {
    echo "$(tput bold)${1}$(tput sgr 0)"
    read -p "Sure to run this line?"
    eval "$1"
}

preval "svn delete $(zbx.resolve.remote)/branches/dev/$(zbx.resolve.branch) -m \"$(zbx.flags -) [$(zbx.resolve.branch)] removing merged development branch\""
