#!/bin/bash
[[ $1 == -h ]] && zbx.-h $0 && exit
[ -z $1 ] && $0 -h && exit

## Choose one of:
while [[ $# > 0 ]];do case $1 in
    #- prind command only, do not execute
    -p |--print-cmd)__print_cmd=1;;
    #- stop on failed, errored .. etc
    -s |--stop)__stop=1;;
    #- Use postgres for tests running (relevant for api test) (mysql is default)
    -Pg|--postgress)__postgres_conf=" --db-postgres";;
    #- runs all api tests
    -a |--api-all)__api_all=1;;
    #- runs all unit tests
    -u |--unit-all)__unit_all=1;;
    #- Accepts, value; Query and tests fzf list (multiple);
    -t |--tests)shift;__tests=$1;;
    #- Accepts, value; If given, used as --filter flag for phpunit.
    -f |--filter)shift;__filter=$1;;
    *) echo "Unknown parameter passed: $1"; exit 1;;
esac;shift;done

[ -z $__api_all ] && [ -z $__unit_all ] && echo \
    "one of --api-all --unit-all flags must be used" && exit 2;

tests_dir=$(zbx.resolve --working-dir)/frontends/php/tests

[ ! -d $tests_dir/vendor ] && echo \
    "did you forget to zbx.make --phpunit?" && exit 2;

branch_name="$(zbx.resolve --branch)"
dbname=${branch_name}_test_api

[ ! -z $__api_all ] && [ -z $(
    mysql -h127.0.0.1 -uroot -e "show databases" | grep "$dbname"
) ] && echo \
    "did not find DB:$dbname, did ypu forget to zbx.make --db-api?" && exit 2;

cd $tests_dir

unit_all() {
    served_tests_dir=$(
        rm -fr ../../php-test-unit;
        mkdir -p ../../php-test-unit;
        cp -r ./.. ../../php-test-unit;
        cd ../../php-test-unit && echo $PWD;
    )
    cd $served_tests_dir/tests/unit;
    wget https://phar.phpunit.de/phpunit-5.3.2.phar
    # NOTE: it does not work with php v7.3
    chmod +x phpunit-5.3.2.phar

    filter=$([ ! -z $__filter ] && echo -n "--filter='$__filter'")
    php56 -c /etc/php/php.ini phpunit-5.3.2.phar $filter .
};[ ! -z $__unit_all ] && unit_all

api_all() {
    echo "
    <?php
    define('PHPUNIT_URL', '$(zbx.resolve --web-api-test-url)');
    define('PHPUNIT_LOGIN_NAME', 'Admin');
    define('PHPUNIT_LOGIN_PWD', 'zabbix');
    define('PHPUNIT_BASEDIR', __DIR__);
    define('PHPUNIT_SCREENSHOT_DIR', '{SCREENSHOT_DIR}');
    define('PHPUNIT_SCREENSHOT_URL', '{SCREENSHOT_URL}');
    define('PHPUNIT_ENABLE_DATA_LIMITS', false);
    " > ./bootstrap.php

    served_tests_dir=$(
        rm -fr ../../php-test-api;
        mkdir -p ../../php-test-api;
        cp -r ./.. ../../php-test-api;
        cd ../../php-test-api && echo $PWD;
    )

    cd $served_tests_dir/tests;
    zbx.config --api-tests-conf $__postgres_conf

    echo "Tests run on src copy. Work on safe."

    tests=$([ ! -z $__tests ] && find api_json -type f | grep "/test" | fzf --select-1 --height 7 -m -q $__tests)
    filter=$([ ! -z $__filter ] && echo -n "--filter='$__filter'")
    # stopped=$([ ! -z $__stop ] && echo -n "
    #     --stop-on-error \\
    #     --stop-on-failure \\
    #     --stop-on-warning \\
    #     --stop-on-risky \\
    #     --stop-on-skipped \\
    #     --stop-on-incomplete
    # ")

    # cmd="php56 -c /etc/php/php.ini ./vendor/bin/phpunit \
    cmd="./vendor/bin/phpunit \
        --verbose \
        --bootstrap=./bootstrap.php \
        --color=always \
        $stopped \
        $filter \
        $tests \
        $served_tests_dir/tests/api_json/ApiJsonTests.php;"

    if [ ! -z $__print_cmd ]; then
        echo
        echo "==cut=="
        echo "cd $served_tests_dir/tests;"
        echo $cmd;
        echo "==cut=="
    else
        eval $cmd;
    fi
};[ ! -z $__api_all ] && api_all
