#!/bin/bash
## Sender aliases.
## Sane defaults are prefilled: `-z localhost -p 10051 $@ -v`.
[[ $1 == -h ]] && zbx.-h "$0" && exit

#- To see zabbix sender specific help
#- --help

build_prefix=$(zbx.resolve --build-prefix)

binary=$build_prefix/bin/zabbix_sender

$binary -z localhost -p 10051 "$@" -v
